name: Bump version
on:
  push:
    branches:
      - 'main'
jobs:
  bump-version:
    name: 'Bump Version on master'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}
      - name:  'Automated Version Bump'
        uses:  'phips28/gh-action-bump-version@master'
        with:
          tag-prefix:  'v'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
